// <auto-generated />
using System;
using MiPeluqueria.Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiPeluqueria.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003051507_Seed_Admin_Usuario")]
    partial class Seed_Admin_Usuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TipoCabelloId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoRostroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TipoCabelloId");

                    b.HasIndex("TipoRostroId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.FichaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetalleFormulaTintura")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NotasSensibilidadAlergias")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex("TurnoId");

                    b.ToTable("FichasTecnicas");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.TipoCabello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TiposCabello");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.TipoRostro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TiposRostro");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.HistorialSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MotivoFallo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSesiones");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8075),
                            IsDeleted = false,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8077),
                            IsDeleted = false,
                            Nombre = "Recepcionista"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8079),
                            IsDeleted = false,
                            Nombre = "Peluquero"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8080),
                            IsDeleted = false,
                            Nombre = "Cliente"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8081),
                            IsDeleted = false,
                            Nombre = "Cajero"
                        });
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("bit");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoVerificacion")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAceptacionTerminos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AceptaTerminos = true,
                            Activo = true,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8111),
                            Email = "admin@tesis.com",
                            EmailVerificado = true,
                            IntentosFallidos = 0,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$0nN01jB5P169DXZgN/.hCeeNInhV/9tYkH.fK5v4a9jR1LqFkI5C6",
                            RolId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProducto");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsParaVenta")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimoAlerta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.BloqueoHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeluqueroId");

                    b.ToTable("BloqueosHorario");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.CategoriaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoriasServicio");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.EstadoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EstadosTurno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7907),
                            IsDeleted = false,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7909),
                            IsDeleted = false,
                            Nombre = "Confirmado"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7911),
                            IsDeleted = false,
                            Nombre = "En Proceso"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7912),
                            IsDeleted = false,
                            Nombre = "Completado"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7914),
                            IsDeleted = false,
                            Nombre = "Cancelado"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(7915),
                            IsDeleted = false,
                            Nombre = "No Asistió"
                        });
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.HistorialEstadoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstadoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("HistorialEstadoTurnos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.HorarioLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeluqueroId");

                    b.ToTable("HorariosLaborales");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.MotivoCancelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MotivosCancelacion");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Peluquero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ColorAgendaHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Peluqueros");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.PeluqueroEspecialidad", b =>
                {
                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.HasKey("PeluqueroId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("PeluqueroEspecialidades", (string)null);
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoTotalEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MotivoCancelacionId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MotivoCancelacionId");

                    b.HasIndex("PeluqueroId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.TurnoServicio", b =>
                {
                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutosHistorica")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioHistorico")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TurnoId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("TurnoServicios", (string)null);
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.ComisionesConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeServicio")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeVentaProducto")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex("ServicioId");

                    b.ToTable("ComisionesConfigs");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.DetalleLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DetalleVentaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoComisionCalculado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.ToTable("DetallesLiquidacion");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoItem")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalProductos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalServicios")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeluqueroId");

                    b.ToTable("Liquidaciones");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MediosPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8038),
                            IsDeleted = false,
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8039),
                            IsDeleted = false,
                            Nombre = "Tarjeta de Débito"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8041),
                            IsDeleted = false,
                            Nombre = "Tarjeta de Crédito"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8042),
                            IsDeleted = false,
                            Nombre = "Transferencia / Alias"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8044),
                            IsDeleted = false,
                            Nombre = "Mercado Pago QR"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8045),
                            IsDeleted = false,
                            Nombre = "Billetera Virtual (Otra)"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 10, 3, 5, 15, 6, 820, DateTimeKind.Utc).AddTicks(8048),
                            IsDeleted = false,
                            Nombre = "Canje / Cortesía"
                        });
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SesionCajaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SesionCajaId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.SesionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Diferencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EstadoAbierta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MontoFinalEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoFinalReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SesionesCaja");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SesionCajaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SesionCajaId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.Cliente", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Clientes.TipoCabello", "TipoCabello")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoCabelloId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Clientes.TipoRostro", "TipoRostro")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoRostroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoCabello");

                    b.Navigation("TipoRostro");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.FichaTecnica", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Clientes.Cliente", "Cliente")
                        .WithMany("FichasTecnicas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany("FichasTecnicas")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Peluquero");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.HistorialSesion", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.Usuario", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany()
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peluquero");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.MovimientoStock", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Stock.Producto", "Producto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.Producto", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Stock.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Stock.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.BloqueoHorario", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany("BloqueosHorario")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.HistorialEstadoTurno", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.EstadoTurno", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.EstadoTurno", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Turno", "Turno")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.HorarioLaboral", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany("HorariosLaborales")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.PeluqueroEspecialidad", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Especialidad", "Especialidad")
                        .WithMany("PeluqueroEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany("PeluqueroEspecialidades")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Servicio", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Turno", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Clientes.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.EstadoTurno", "Estado")
                        .WithMany("Turnos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.MotivoCancelacion", "MotivoCancelacion")
                        .WithMany("TurnosCancelados")
                        .HasForeignKey("MotivoCancelacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany("Turnos")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("MotivoCancelacion");

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.TurnoServicio", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Servicio", "Servicio")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Turno", "Turno")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.ComisionesConfig", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany()
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Peluquero");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.DetalleLiquidacion", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Ventas.Liquidacion", "Liquidacion")
                        .WithMany("DetallesLiquidacion")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Ventas.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Liquidacion", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Peluquero", "Peluquero")
                        .WithMany()
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.MovimientoCaja", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Ventas.SesionCaja", "SesionCaja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SesionCaja");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Pago", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Ventas.MedioPago", "MedioPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Ventas.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Venta", b =>
                {
                    b.HasOne("MiPeluqueria.Api.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MiPeluqueria.Api.Models.Ventas.SesionCaja", "SesionCaja")
                        .WithMany("Ventas")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiPeluqueria.Api.Models.Turnos.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("SesionCaja");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.Cliente", b =>
                {
                    b.Navigation("FichasTecnicas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.TipoCabello", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Clientes.TipoRostro", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Seguridad.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.Producto", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Stock.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Especialidad", b =>
                {
                    b.Navigation("PeluqueroEspecialidades");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.EstadoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.MotivoCancelacion", b =>
                {
                    b.Navigation("TurnosCancelados");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Peluquero", b =>
                {
                    b.Navigation("BloqueosHorario");

                    b.Navigation("FichasTecnicas");

                    b.Navigation("HorariosLaborales");

                    b.Navigation("PeluqueroEspecialidades");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Servicio", b =>
                {
                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Turnos.Turno", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Liquidacion", b =>
                {
                    b.Navigation("DetallesLiquidacion");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.MedioPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.SesionCaja", b =>
                {
                    b.Navigation("MovimientosCaja");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("MiPeluqueria.Api.Models.Ventas.Venta", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
